// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4zNwt-8iDL0RdVvy9RFYOzgxwo2L1Dl8',
    appId: '1:186156667190:web:a1c068301c543d952d2397',
    messagingSenderId: '186156667190',
    projectId: 'projectlab-b2e04',
    authDomain: 'projectlab-b2e04.firebaseapp.com',
    storageBucket: 'projectlab-b2e04.firebasestorage.app',
    measurementId: 'G-2KC6PH6L1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzMqaBf3PPLhgTpdzNHdn8jyx32RGOxc0',
    appId: '1:186156667190:android:579f85cfae1f93842d2397',
    messagingSenderId: '186156667190',
    projectId: 'projectlab-b2e04',
    storageBucket: 'projectlab-b2e04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAowQtJ69tLvXLQaE0bNoXfj5aaHBZ6W-M',
    appId: '1:186156667190:ios:a77c0a83fb056cf62d2397',
    messagingSenderId: '186156667190',
    projectId: 'projectlab-b2e04',
    storageBucket: 'projectlab-b2e04.firebasestorage.app',
    iosBundleId: 'com.example.leeWenZheDicksonB250052a',
  );
}
